import Head from "next/head";
import CreateGame from "../components/CreateGame";
import Newgame from "./game";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CreateGame />
        <Newgame />
      </main>
    </div>
  );
}
