import Head from "next/head";
import Image from "next/image";
import appLogo from "../appLogo.webp";
import CreateGame from "../components/CreateGame";
import Newgame from "./game";
import styled from "styled-components";
import { useState } from "react";
import { nanoid } from "nanoid";

export default function Home() {
  const [gameScores, setGameScores] = useState([]);
  console.log(gameScores);

  return (
    <div>
      <Head>
        <title>Scoreboard Keeper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FlexFrame>
          <Header>
            <Image width="200" height="200" src={appLogo} />
            <AppTitle>Scoreboard Keeper</AppTitle>
          </Header>
          <CreateGame onCreateGame={createGame} />
        </FlexFrame>
      </main>
    </div>
  );

  function createGame({ gameName, gamePlayers }) {
    setGameScores([
      ...gameScores,
      {
        id: nanoid(),
        gameName: gameName,
        gamePlayers: gamePlayers,
      },
    ]);
  }
}

const FlexFrame = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const Header = styled.header`
  display: flex;
  width: 700px;
  align-items: center;
  gap: 1rem;
`;

const AppTitle = styled.h1`
  font-size: 3rem; ;
`;
